// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	models "PinguinMobile/models"

	mock "github.com/stretchr/testify/mock"
)

// ChatRepository is an autogenerated mock type for the ChatRepository type
type ChatRepository struct {
	mock.Mock
}

// DeleteMessage provides a mock function with given fields: messageID
func (_m *ChatRepository) DeleteMessage(messageID uint) error {
	ret := _m.Called(messageID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(messageID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetChannelsList provides a mock function with given fields: parentID
func (_m *ChatRepository) GetChannelsList(parentID string) ([]string, error) {
	ret := _m.Called(parentID)

	if len(ret) == 0 {
		panic("no return value specified for GetChannelsList")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]string, error)); ok {
		return rf(parentID)
	}
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(parentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(parentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFamilyMessages provides a mock function with given fields: parentID, channel, limit, offset
func (_m *ChatRepository) GetFamilyMessages(parentID string, channel string, limit int, offset int) ([]models.ChatMessage, error) {
	ret := _m.Called(parentID, channel, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetFamilyMessages")
	}

	var r0 []models.ChatMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, int, int) ([]models.ChatMessage, error)); ok {
		return rf(parentID, channel, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(string, string, int, int) []models.ChatMessage); ok {
		r0 = rf(parentID, channel, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.ChatMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, int, int) error); ok {
		r1 = rf(parentID, channel, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPrivateMessages provides a mock function with given fields: parentID, user1ID, user2ID, limit, offset
func (_m *ChatRepository) GetPrivateMessages(parentID string, user1ID string, user2ID string, limit int, offset int) ([]models.ChatMessage, error) {
	ret := _m.Called(parentID, user1ID, user2ID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetPrivateMessages")
	}

	var r0 []models.ChatMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string, int, int) ([]models.ChatMessage, error)); ok {
		return rf(parentID, user1ID, user2ID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(string, string, string, int, int) []models.ChatMessage); ok {
		r0 = rf(parentID, user1ID, user2ID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.ChatMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, string, int, int) error); ok {
		r1 = rf(parentID, user1ID, user2ID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUnreadMessagesCount provides a mock function with given fields: parentID, userID, channel
func (_m *ChatRepository) GetUnreadMessagesCount(parentID string, userID string, channel string) (int64, error) {
	ret := _m.Called(parentID, userID, channel)

	if len(ret) == 0 {
		panic("no return value specified for GetUnreadMessagesCount")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) (int64, error)); ok {
		return rf(parentID, userID, channel)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) int64); ok {
		r0 = rf(parentID, userID, channel)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(parentID, userID, channel)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUnreadPrivateCount provides a mock function with given fields: parentID, recipientID
func (_m *ChatRepository) GetUnreadPrivateCount(parentID string, recipientID string) (int64, error) {
	ret := _m.Called(parentID, recipientID)

	if len(ret) == 0 {
		panic("no return value specified for GetUnreadPrivateCount")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (int64, error)); ok {
		return rf(parentID, recipientID)
	}
	if rf, ok := ret.Get(0).(func(string, string) int64); ok {
		r0 = rf(parentID, recipientID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(parentID, recipientID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarkAsRead provides a mock function with given fields: messageIDs
func (_m *ChatRepository) MarkAsRead(messageIDs []uint) error {
	ret := _m.Called(messageIDs)

	if len(ret) == 0 {
		panic("no return value specified for MarkAsRead")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]uint) error); ok {
		r0 = rf(messageIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ModerateMessage provides a mock function with given fields: messageID, isHidden
func (_m *ChatRepository) ModerateMessage(messageID uint, isHidden bool) error {
	ret := _m.Called(messageID, isHidden)

	if len(ret) == 0 {
		panic("no return value specified for ModerateMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, bool) error); ok {
		r0 = rf(messageID, isHidden)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveMessage provides a mock function with given fields: message
func (_m *ChatRepository) SaveMessage(message *models.ChatMessage) error {
	ret := _m.Called(message)

	if len(ret) == 0 {
		panic("no return value specified for SaveMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.ChatMessage) error); ok {
		r0 = rf(message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewChatRepository creates a new instance of ChatRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChatRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ChatRepository {
	mock := &ChatRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
