// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	models "PinguinMobile/models"

	mock "github.com/stretchr/testify/mock"
)

// ChildRepository is an autogenerated mock type for the ChildRepository type
type ChildRepository struct {
	mock.Mock
}

// AddTimeBlockedApps provides a mock function with given fields: childID, timeBlocks
func (_m *ChildRepository) AddTimeBlockedApps(childID uint, timeBlocks []models.AppTimeBlock) error {
	ret := _m.Called(childID, timeBlocks)

	if len(ret) == 0 {
		panic("no return value specified for AddTimeBlockedApps")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, []models.AppTimeBlock) error); ok {
		r0 = rf(childID, timeBlocks)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CountByCode provides a mock function with given fields: code, count
func (_m *ChildRepository) CountByCode(code string, count *int64) error {
	ret := _m.Called(code, count)

	if len(ret) == 0 {
		panic("no return value specified for CountByCode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *int64) error); ok {
		r0 = rf(code, count)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: child
func (_m *ChildRepository) Delete(child models.Child) error {
	ret := _m.Called(child)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(models.Child) error); ok {
		r0 = rf(child)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByCode provides a mock function with given fields: code
func (_m *ChildRepository) FindByCode(code string) (models.Child, error) {
	ret := _m.Called(code)

	if len(ret) == 0 {
		panic("no return value specified for FindByCode")
	}

	var r0 models.Child
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (models.Child, error)); ok {
		return rf(code)
	}
	if rf, ok := ret.Get(0).(func(string) models.Child); ok {
		r0 = rf(code)
	} else {
		r0 = ret.Get(0).(models.Child)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByFirebaseUID provides a mock function with given fields: firebaseUID
func (_m *ChildRepository) FindByFirebaseUID(firebaseUID string) (models.Child, error) {
	ret := _m.Called(firebaseUID)

	if len(ret) == 0 {
		panic("no return value specified for FindByFirebaseUID")
	}

	var r0 models.Child
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (models.Child, error)); ok {
		return rf(firebaseUID)
	}
	if rf, ok := ret.Get(0).(func(string) models.Child); ok {
		r0 = rf(firebaseUID)
	} else {
		r0 = ret.Get(0).(models.Child)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(firebaseUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTimeBlockedApps provides a mock function with given fields: childID
func (_m *ChildRepository) GetTimeBlockedApps(childID uint) ([]models.AppTimeBlock, error) {
	ret := _m.Called(childID)

	if len(ret) == 0 {
		panic("no return value specified for GetTimeBlockedApps")
	}

	var r0 []models.AppTimeBlock
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) ([]models.AppTimeBlock, error)); ok {
		return rf(childID)
	}
	if rf, ok := ret.Get(0).(func(uint) []models.AppTimeBlock); ok {
		r0 = rf(childID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.AppTimeBlock)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(childID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveTimeBlockedApps provides a mock function with given fields: childID, appPackages
func (_m *ChildRepository) RemoveTimeBlockedApps(childID uint, appPackages []string) error {
	ret := _m.Called(childID, appPackages)

	if len(ret) == 0 {
		panic("no return value specified for RemoveTimeBlockedApps")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, []string) error); ok {
		r0 = rf(childID, appPackages)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Save provides a mock function with given fields: child
func (_m *ChildRepository) Save(child models.Child) error {
	ret := _m.Called(child)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(models.Child) error); ok {
		r0 = rf(child)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewChildRepository creates a new instance of ChildRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChildRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ChildRepository {
	mock := &ChildRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
