// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	models "PinguinMobile/models"

	mock "github.com/stretchr/testify/mock"
)

// ParentRepository is an autogenerated mock type for the ParentRepository type
type ParentRepository struct {
	mock.Mock
}

// CountByCode provides a mock function with given fields: code, count
func (_m *ParentRepository) CountByCode(code string, count *int64) error {
	ret := _m.Called(code, count)

	if len(ret) == 0 {
		panic("no return value specified for CountByCode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *int64) error); ok {
		r0 = rf(code, count)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteByFirebaseUID provides a mock function with given fields: firebaseUID
func (_m *ParentRepository) DeleteByFirebaseUID(firebaseUID string) error {
	ret := _m.Called(firebaseUID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByFirebaseUID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(firebaseUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByCode provides a mock function with given fields: code
func (_m *ParentRepository) FindByCode(code string) (models.Parent, error) {
	ret := _m.Called(code)

	if len(ret) == 0 {
		panic("no return value specified for FindByCode")
	}

	var r0 models.Parent
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (models.Parent, error)); ok {
		return rf(code)
	}
	if rf, ok := ret.Get(0).(func(string) models.Parent); ok {
		r0 = rf(code)
	} else {
		r0 = ret.Get(0).(models.Parent)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByEmail provides a mock function with given fields: email
func (_m *ParentRepository) FindByEmail(email string) (models.Parent, error) {
	ret := _m.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 models.Parent
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (models.Parent, error)); ok {
		return rf(email)
	}
	if rf, ok := ret.Get(0).(func(string) models.Parent); ok {
		r0 = rf(email)
	} else {
		r0 = ret.Get(0).(models.Parent)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByFirebaseUID provides a mock function with given fields: firebaseUID
func (_m *ParentRepository) FindByFirebaseUID(firebaseUID string) (models.Parent, error) {
	ret := _m.Called(firebaseUID)

	if len(ret) == 0 {
		panic("no return value specified for FindByFirebaseUID")
	}

	var r0 models.Parent
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (models.Parent, error)); ok {
		return rf(firebaseUID)
	}
	if rf, ok := ret.Get(0).(func(string) models.Parent); ok {
		r0 = rf(firebaseUID)
	} else {
		r0 = ret.Get(0).(models.Parent)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(firebaseUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: parent
func (_m *ParentRepository) Save(parent models.Parent) error {
	ret := _m.Called(parent)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(models.Parent) error); ok {
		r0 = rf(parent)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewParentRepository creates a new instance of ParentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewParentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ParentRepository {
	mock := &ParentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
